build: Build an installation archive

diff --git a/.github/workflows/build_crosscompile.yml b/.github/workflows/build_crosscompile.yml
--- a/.github/workflows/build_crosscompile.yml
+++ b/.github/workflows/build_crosscompile.yml
@@ -55,13 +55,14 @@ jobs:
       
       - name: Build debug
         run: |
+          # build plugin
           cd ${{ env.PROJECT_NAME}}/build
           PATH=${TOOLCHAIN_PATH}/bin:${TOOLCHAIN_PATH}/sbin:$PATH
           CPU_CORES=$(getconf _NPROCESSORS_ONLN)
           echo "Numbers of CPU cores for make: $CPU_CORES"
           make -j$CPU_CORES
-          cp dock.json ${{ env.YIO_BIN }}
-          cp version.txt ${{ env.YIO_BIN }}
+
+          # log build information
           echo "GitHub Actions debug build
           $(date)
           GIT branch: $(git rev-parse --abbrev-ref HEAD)
@@ -79,12 +80,33 @@ jobs:
           $(cpp --version)
           " > ${{ env.YIO_BIN }}/build.info
 
+      - name: Get plugin version
+        run: |
+          cd ${{ env.PROJECT_NAME}}/build
+          read -r PLUGIN_VERSION<version.txt
+          echo "Plugin version: $PLUGIN_VERSION"
+          echo "::set-env name=APP_VERSION::$PLUGIN_VERSION"
+
+      - name: Create debug installation
+        run: |
+          echo "APP_VERSION: $APP_VERSION"
+          # copy additional files for the installation archive
+          cd ${{ env.PROJECT_NAME}}/build
+          cp dock.json ${{ env.YIO_BIN }}
+          cp version.txt ${{ env.YIO_BIN }}
+          # hooks are optional: don't fail if missing
+          cp -r hooks ${{ env.YIO_BIN }} || :
+          # compress plugin
+          cd ${{ env.YIO_BIN }}
+          tar -czvf plugins.tar.gz plugins
+          rm -Rf plugins
+
       - uses: actions/upload-artifact@v1
         id: upload_artifact_debug
         with:
           # Dear GitHub: dealing with env resolution is a PITA! ${{ env.YIO_BIN }} leads to a wrong path!!!
           path: ../binaries
-          name: ${{ env.APP_NAME}}-Qt${{ env.QT_VERSION }}-debug-ARM-RPi0
+          name: ${{ env.APP_NAME}}-${{ env.APP_VERSION}}-debug-release
 
       - name: Configure release
         run: |
@@ -125,9 +147,23 @@ jobs:
           $(cpp --version)
           " > ${{ env.YIO_BIN }}/build.info
 
+      - name: Create release installation
+        run: |
+          echo "APP_VERSION: $APP_VERSION"
+          # copy additional files for the installation archive
+          cd ${{ env.PROJECT_NAME}}/build
+          cp dock.json ${{ env.YIO_BIN }}
+          cp version.txt ${{ env.YIO_BIN }}
+          # hooks are optional: don't fail if missing
+          cp -r hooks ${{ env.YIO_BIN }} || :
+          # compress plugin
+          cd ${{ env.YIO_BIN }}
+          tar -czvf plugins.tar.gz plugins
+          rm -Rf plugins
+
       - uses: actions/upload-artifact@v1
         id: upload_artifact_release
         with:
           # Dear GitHub: dealing with env resolution is a PITA! ${{ env.YIO_BIN }} leads to a wrong path!!!
           path: ../binaries
-          name: ${{ env.APP_NAME}}-Qt${{ env.QT_VERSION }}-release-ARM-RPi0
+          name: ${{ env.APP_NAME}}-${{ env.APP_VERSION}}-remote-release
